// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPYrFbmQzoGFJyNTPc6_r-Nwo_LQAXt14',
    appId: '1:446607982003:web:qahwatapp',
    messagingSenderId: '446607982003',
    projectId: 'qahwatapp',
    authDomain: 'qahwatapp.firebaseapp.com',
    databaseURL:
        'https://qahwatapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qahwatapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPYrFbmQzoGFJyNTPc6_r-Nwo_LQAXt14',
    appId: '1:446607982003:android:31d906b11afa121189dfc6',
    messagingSenderId: '446607982003',
    projectId: 'qahwatapp',
    databaseURL:
        'https://qahwatapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qahwatapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPYrFbmQzoGFJyNTPc6_r-Nwo_LQAXt14',
    appId: '1:446607982003:ios:d7e83ac110607e0389dfc6',
    messagingSenderId: '446607982003',
    projectId: 'qahwatapp',
    databaseURL:
        'https://qahwatapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qahwatapp.appspot.com',
    iosBundleId: 'qahwatalemarat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPYrFbmQzoGFJyNTPc6_r-Nwo_LQAXt14',
    appId: '1:446607982003:ios:d7e83ac110607e0389dfc6',
    messagingSenderId: '446607982003',
    projectId: 'qahwatapp',
    databaseURL:
        'https://qahwatapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qahwatapp.appspot.com',
    iosBundleId: 'qahwatalemarat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPYrFbmQzoGFJyNTPc6_r-Nwo_LQAXt14',
    appId: '1:446607982003:web:qahwatapp',
    messagingSenderId: '446607982003',
    projectId: 'qahwatapp',
    authDomain: 'qahwatapp.firebaseapp.com',
    databaseURL:
        'https://qahwatapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qahwatapp.appspot.com',
  );
}
